// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'eu-central-1:a8b5f987-8017-4abc-9e7e-007c6ac9cca5',
aws_cognito_region : 'eu-central-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'atlantm-hosting-mobilehub-1203561977',
aws_content_delivery_bucket_region : 'eu-central-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd13jo9ph83mrlq.cloudfront.net',
aws_mobile_analytics_app_id : 'd2b24a923fc04ce3ba67e7fdd8367cd2',
aws_project_id : '7b4c4eda-f919-42b8-acb2-037a2709997f',
aws_project_name : 'Atlant-M',
aws_project_region : 'eu-central-1',
aws_resource_name_prefix : 'atlantm-mobilehub-1203561977',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});