export const SERVICE_ORDER__REQUEST = 'SERVICE_ORDER__REQUEST';
export const SERVICE_ORDER__SUCCESS = 'SERVICE_ORDER__SUCCESS';
export const SERVICE_ORDER__FAIL = 'SERVICE_ORDER__FAIL';

export const SERVICE_CAR__FILL = 'SERVICE_CAR__FILL';
export const SERVICE_DATE__FILL = 'SERVICE_DATE__FILL';
