export const SERVICE_ORDER__REQUEST = 'SERVICE_ORDER__REQUEST';
export const SERVICE_ORDER__SUCCESS = 'SERVICE_ORDER__SUCCESS';
export const SERVICE_ORDER__FAIL = 'SERVICE_ORDER__FAIL';

export const PARTS_ORDER__REQUEST = 'PARTS_ORDER__REQUEST';
export const PARTS_ORDER__SUCCESS = 'PARTS_ORDER__SUCCESS';
export const PARTS_ORDER__FAIL = 'PARTS_ORDER__FAIL';

export const SERVICE_DATE__FILL = 'SERVICE_DATE__FILL';
