pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:zavarkateam/atlantm-mobile.git
          - cd atlantm-mobile.git
          - git push --mirror git@github.com:zavarkateam/atlantm-mobile.git