export const USED_CAR_LIST__REQUEST = 'USED_CAR_LIST__REQUEST';
export const USED_CAR_LIST__SUCCESS = 'USED_CAR_LIST__SUCCESS';
export const USED_CAR_LIST__FAIL = 'USED_CAR_LIST__FAIL';
export const USED_CAR_LIST__RESET = 'USED_CAR_LIST__RESET';
export const USED_CAR_LIST_UPDATE__SET = 'USED_CAR_LIST_UPDATE__SET';
export const USED_CAR_LIST_STOP_UPDATE__SET = 'USED_CAR_LIST_STOP_UPDATE__SET';

export const USED_CAR_DETAILS__REQUEST = 'USED_CAR_DETAILS__REQUEST';
export const USED_CAR_DETAILS__SUCCESS = 'USED_CAR_DETAILS__SUCCESS';
export const USED_CAR_DETAILS__FAIL = 'USED_CAR_DETAILS__FAIL';
export const USED_CAR_DETAILS_PHOTO_VIEWER__OPEN = 'USED_CAR_DETAILS_PHOTO_VIEWER__OPEN';
export const USED_CAR_DETAILS_PHOTO_VIEWER__CLOSE = 'USED_CAR_DETAILS_PHOTO_VIEWER__CLOSE';
export const USED_CAR_DETAILS_PHOTO_VIEWER_INDEX__UPDATE = 'USED_CAR_DETAILS_PHOTO_VIEWER_INDEX__UPDATE';
export const USED_CAR_DETAILS_PHOTO_VIEWER_ITEMS__SET = 'USED_CAR_DETAILS_PHOTO_VIEWER_ITEMS__SET';

export const USED_CAR_PRICE_FILTER__SHOW = 'USED_CAR_PRICE_FILTER__SHOW';
export const USED_CAR_PRICE_FILTER__HIDE = 'USED_CAR_PRICE_FILTER__HIDE';

export const USED_CAR_CITY__SELECT = 'USED_CAR_CITY__SELECT';
export const USED_CAR_PRICE_RANGE__SELECT = 'USED_CAR_PRICE_RANGE__SELECT';
export const USED_CAR_REGION__SELECT = 'USED_CAR_REGION__SELECT';

export const CATALOG_CITY__SELECT = 'CATALOG_CITY__SELECT';

export const CATALOG_DEALER__REQUEST = 'CATALOG_DEALER__REQUEST';
export const CATALOG_DEALER__SUCCESS = 'CATALOG_DEALER__SUCCESS';
export const CATALOG_DEALER__FAIL = 'CATALOG_DEALER__FAIL';

export const CATALOG_ORDER__REQUEST = 'CATALOG_ORDER__REQUEST';
export const CATALOG_ORDER__SUCCESS = 'CATALOG_ORDER__SUCCESS';
export const CATALOG_ORDER__FAIL = 'CATALOG_ORDER__FAIL';

export const TESTDRIVE_ORDER__REQUEST = 'TESTDRIVE_ORDER__REQUEST';
export const TESTDRIVE_ORDER__SUCCESS = 'TESTDRIVE_ORDER__SUCCESS';
export const TESTDRIVE_ORDER__FAIL = 'TESTDRIVE_ORDER__FAIL';

export const TESTDRIVE_USED_ORDER__REQUEST = 'TESTDRIVE_USED_ORDER__REQUEST';
export const TESTDRIVE_USED_ORDER__SUCCESS = 'TESTDRIVE_USED_ORDER__SUCCESS';
export const TESTDRIVE_USED_ORDER__FAIL = 'TESTDRIVE_USED_ORDER__FAIL';

export const CREDIT_ORDER__REQUEST = 'CREDIT_ORDER__REQUEST';
export const CREDIT_ORDER__SUCCESS = 'CREDIT_ORDER__SUCCESS';
export const CREDIT_ORDER__FAIL = 'CREDIT_ORDER__FAIL';

export const MYPRICE_ORDER__REQUEST = 'MYPRICE_ORDER__REQUEST';
export const MYPRICE_ORDER__SUCCESS = 'MYPRICE_ORDER__SUCCESS';
export const MYPRICE_ORDER__FAIL = 'MYPRICE_ORDER__FAIL';

export const CATALOG_ORDER_COMMENT__FILL = 'CATALOG_ORDER_COMMENT__FILL';

// newcar

export const NEW_CAR_CITY__SELECT = 'NEW_CAR_CITY__SELECT';
export const NEW_CAR_REGION__SELECT = 'NEW_CAR_REGION__SELECT';

export const NEW_CAR_FILTER_DATA__REQUEST = 'NEW_CAR_FILTER_DATA__REQUEST';
export const NEW_CAR_FILTER_DATA__SUCCESS = 'NEW_CAR_FILTER_DATA__SUCCESS';
export const NEW_CAR_FILTER_DATA__FAIL = 'NEW_CAR_FILTER_DATA__FAIL';

export const NEW_CAR_BY_FILTER__REQUEST = 'NEW_CAR_BY_FILTER__REQUEST';
export const NEW_CAR_BY_FILTER__SUCCESS = 'NEW_CAR_BY_FILTER__SUCCESS';
export const NEW_CAR_BY_FILTER__FAIL = 'NEW_CAR_BY_FILTER__FAIL';

export const NEW_CAR_FILTER_BRANDS__SELECT = 'NEW_CAR_FILTER_BRANDS__SELECT';
export const NEW_CAR_FILTER_MODELS__SELECT = 'NEW_CAR_FILTER_MODELS__SELECT';
export const NEW_CAR_FILTER_BODY__SELECT = 'NEW_CAR_FILTER_BODY__SELECT';
export const NEW_CAR_FILTER_ENGINE_TYPE__SELECT = 'NEW_CAR_FILTER_ENGINE_TYPE__SELECT';
export const NEW_CAR_FILTER_GEARBOX__SELECT = 'NEW_CAR_FILTER_GEARBOX__SELECT';
export const NEW_CAR_FILTER_DRIVE__SELECT = 'NEW_CAR_FILTER_DRIVE__SELECT';
export const NEW_CAR_FILTER_PRICE__SELECT = 'NEW_CAR_FILTER_PRICE__SELECT';
export const NEW_CAR_FILTER_PRICE__SHOW = 'NEW_CAR_FILTER_PRICE__SHOW';
export const NEW_CAR_FILTER_PRICE__HIDE = 'NEW_CAR_FILTER_PRICE__HIDE';
export const NEW_CAR_FILTER_PRICE_SPECIAL__SET = 'NEW_CAR_FILTER_PRICE_SPECIAL__SET';

export const NEW_CAR_DETAILS__REQUEST = 'NEW_CAR_DETAILS__REQUEST';
export const NEW_CAR_DETAILS__SUCCESS = 'NEW_CAR_DETAILS__SUCCESS';
export const NEW_CAR_DETAILS__FAIL = 'NEW_CAR_DETAILS__FAIL';

export const TD_CAR_DETAILS__REQUEST = 'TD_CAR_DETAILS__REQUEST';
export const TD_CAR_DETAILS__SUCCESS = 'TD_CAR_DETAILS__SUCCESS';
export const TD_CAR_DETAILS__FAIL = 'TD_CAR_DETAILS__FAIL';

export const NEW_CAR_DETAILS_PHOTO_VIEWER__OPEN = 'NEW_CAR_DETAILS_PHOTO_VIEWER__OPEN';
export const NEW_CAR_DETAILS_PHOTO_VIEWER__CLOSE = 'NEW_CAR_DETAILS_PHOTO_VIEWER__CLOSE';
export const NEW_CAR_DETAILS_PHOTO_VIEWER_INDEX__UPDATE = 'NEW_CAR_DETAILS_PHOTO_VIEWER_INDEX__UPDATE';
export const NEW_CAR_DETAILS_PHOTO_VIEWER_ITEMS__SET = 'NEW_CAR_DETAILS_PHOTO_VIEWER_ITEMS__SET';

// car cost

export const CAR_COST__REQUEST = 'CAR_COST__REQUEST';
export const CAR_COST__SUCCESS = 'CAR_COST__SUCCESS';
export const CAR_COST__FAIL = 'CAR_COST__FAIL';

export const CAR_COST_PHOTOS__FILL = 'CAR_COST_PHOTOS__FILL';
export const CAR_COST_BRAND__FILL = 'CAR_COST_BRAND__FILL';
export const CAR_COST_MODEL__FILL = 'CAR_COST_MODEL__FILL';
export const CAR_COST_YEAR__SELECT = 'CAR_COST_YEAR__SELECT';
export const CAR_COST_MILEAGE__FILL = 'CAR_COST_MILEAGE__FILL';
export const CAR_COST_MILEAGE_UNIT__SELECT = 'CAR_COST_MILEAGE_UNIT__SELECT';
export const CAR_COST_ENGINE_VOLUME__FILL = 'CAR_COST_ENGINE_VOLUME__FILL';
export const CAR_COST_ENGINE_TYPE__SELECT = 'CAR_COST_ENGINE_TYPE__SELECT';
export const CAR_COST_GEARBOX__SELECT = 'CAR_COST_GEARBOX__SELECT';
export const CAR_COST_COLOR__FILL = 'CAR_COST_COLOR__FILL';
export const CAR_COST_CAR_CONDITION__SELECT = 'CAR_COST_CAR_CONDITION__SELECT';
export const CAR_COST_COMMENT__FILL = 'CAR_COST_COMMENT__FILL';
export const CAR_COST_VIN__FILL = 'CAR_COST_VIN__FILL';

export const ACTION_SAVE_CAR_FILTERS__UPDATE = 'ACTION_SAVE_CAR_FILTERS__UPDATE';
