export const USED_CAR_FILTER_DATA__REQUEST = 'USED_CAR_FILTER_DATA__REQUEST';
export const USED_CAR_FILTER_DATA__SUCCESS = 'USED_CAR_FILTER_DATA__SUCCESS';
export const USED_CAR_FILTER_DATA__FAIL = 'USED_CAR_FILTER_DATA__FAIL';

export const USED_CAR_LIST__REQUEST = 'USED_CAR_LIST__REQUEST';
export const USED_CAR_LIST__SUCCESS = 'USED_CAR_LIST__SUCCESS';
export const USED_CAR_LIST__FAIL = 'USED_CAR_LIST__FAIL';

export const USED_CAR_DETAILS__REQUEST = 'USED_CAR_DETAILS__REQUEST';
export const USED_CAR_DETAILS__SUCCESS = 'USED_CAR_DETAILS__SUCCESS';
export const USED_CAR_DETAILS__FAIL = 'USED_CAR_DETAILS__FAIL';
export const USED_CAR_DETAILS_PHOTO_VIEWER__OPEN =
  'USED_CAR_DETAILS_PHOTO_VIEWER__OPEN';
export const USED_CAR_DETAILS_PHOTO_VIEWER__CLOSE =
  'USED_CAR_DETAILS_PHOTO_VIEWER__CLOSE';
export const USED_CAR_DETAILS_PHOTO_VIEWER_INDEX__UPDATE =
  'USED_CAR_DETAILS_PHOTO_VIEWER_INDEX__UPDATE';
export const USED_CAR_DETAILS_PHOTO_VIEWER_ITEMS__SET =
  'USED_CAR_DETAILS_PHOTO_VIEWER_ITEMS__SET';

export const CATALOG_CITY__SELECT = 'CATALOG_CITY__SELECT';

export const CATALOG_DEALER__REQUEST = 'CATALOG_DEALER__REQUEST';
export const CATALOG_DEALER__SUCCESS = 'CATALOG_DEALER__SUCCESS';
export const CATALOG_DEALER__FAIL = 'CATALOG_DEALER__FAIL';

export const CATALOG_ORDER__REQUEST = 'CATALOG_ORDER__REQUEST';
export const CATALOG_ORDER__SUCCESS = 'CATALOG_ORDER__SUCCESS';
export const CATALOG_ORDER__FAIL = 'CATALOG_ORDER__FAIL';

export const TESTDRIVE_ORDER__REQUEST = 'TESTDRIVE_ORDER__REQUEST';
export const TESTDRIVE_ORDER__SUCCESS = 'TESTDRIVE_ORDER__SUCCESS';
export const TESTDRIVE_ORDER__FAIL = 'TESTDRIVE_ORDER__FAIL';

export const TESTDRIVE_LEAD__REQUEST = 'TESTDRIVE_LEAD__REQUEST';
export const TESTDRIVE_LEAD__SUCCESS = 'TESTDRIVE_LEAD__SUCCESS';
export const TESTDRIVE_LEAD__FAIL = 'TESTDRIVE_LEAD__FAIL';

export const CREDIT_ORDER__REQUEST = 'CREDIT_ORDER__REQUEST';
export const CREDIT_ORDER__SUCCESS = 'CREDIT_ORDER__SUCCESS';
export const CREDIT_ORDER__FAIL = 'CREDIT_ORDER__FAIL';

export const MYPRICE_ORDER__REQUEST = 'MYPRICE_ORDER__REQUEST';
export const MYPRICE_ORDER__SUCCESS = 'MYPRICE_ORDER__SUCCESS';
export const MYPRICE_ORDER__FAIL = 'MYPRICE_ORDER__FAIL';

export const CATALOG_ORDER_COMMENT__FILL = 'CATALOG_ORDER_COMMENT__FILL';

// newcar

export const NEW_CAR_CITY__SELECT = 'NEW_CAR_CITY__SELECT';
export const NEW_CAR_REGION__SELECT = 'NEW_CAR_REGION__SELECT';

export const NEW_CAR_FILTER_DATA__REQUEST = 'NEW_CAR_FILTER_DATA__REQUEST';
export const NEW_CAR_FILTER_DATA__SUCCESS = 'NEW_CAR_FILTER_DATA__SUCCESS';
export const NEW_CAR_FILTER_DATA__FAIL = 'NEW_CAR_FILTER_DATA__FAIL';

export const NEW_CAR_BY_FILTER__REQUEST = 'NEW_CAR_BY_FILTER__REQUEST';
export const NEW_CAR_BY_FILTER__SUCCESS = 'NEW_CAR_BY_FILTER__SUCCESS';
export const NEW_CAR_BY_FILTER__FAIL = 'NEW_CAR_BY_FILTER__FAIL';

export const NEW_CAR_DETAILS__REQUEST = 'NEW_CAR_DETAILS__REQUEST';
export const NEW_CAR_DETAILS__SUCCESS = 'NEW_CAR_DETAILS__SUCCESS';
export const NEW_CAR_DETAILS__FAIL = 'NEW_CAR_DETAILS__FAIL';

export const TD_CAR_DETAILS__REQUEST = 'TD_CAR_DETAILS__REQUEST';
export const TD_CAR_DETAILS__SUCCESS = 'TD_CAR_DETAILS__SUCCESS';
export const TD_CAR_DETAILS__FAIL = 'TD_CAR_DETAILS__FAIL';

export const NEW_CAR_DETAILS_PHOTO_VIEWER__OPEN =
  'NEW_CAR_DETAILS_PHOTO_VIEWER__OPEN';
export const NEW_CAR_DETAILS_PHOTO_VIEWER__CLOSE =
  'NEW_CAR_DETAILS_PHOTO_VIEWER__CLOSE';
export const NEW_CAR_DETAILS_PHOTO_VIEWER_INDEX__UPDATE =
  'NEW_CAR_DETAILS_PHOTO_VIEWER_INDEX__UPDATE';
export const NEW_CAR_DETAILS_PHOTO_VIEWER_ITEMS__SET =
  'NEW_CAR_DETAILS_PHOTO_VIEWER_ITEMS__SET';

// car cost

export const CAR_COST__REQUEST = 'CAR_COST__REQUEST';
export const CAR_COST__SUCCESS = 'CAR_COST__SUCCESS';
export const CAR_COST__FAIL = 'CAR_COST__FAIL';

export const ACTION_SAVE_CAR_FILTERS__UPDATE =
  'ACTION_SAVE_CAR_FILTERS__UPDATE';
