export const USED_CAR_LIST__REQUEST = 'USED_CAR_LIST__REQUEST';
export const USED_CAR_LIST__SUCCESS = 'USED_CAR_LIST__SUCCESS';
export const USED_CAR_LIST__FAIL = 'USED_CAR_LIST__FAIL';
export const USED_CAR_LIST__RESET = 'USED_CAR_LIST__RESET';

export const USED_CAR_PRICE_FILTER__SHOW = 'USED_CAR_PRICE_FILTER__SHOW';
export const USED_CAR_PRICE_FILTER__HIDE = 'USED_CAR_PRICE_FILTER__HIDE';

export const USED_CAR_CITY__SELECT = 'USED_CAR_CITY__SELECT';
export const USED_CAR_PRICE_RANGE__SELECT = 'USED_CAR_PRICE_RANGE__SELECT';
export const USED_CAR_REGION__SELECT = 'USED_CAR_REGION__SELECT';

export const CATALOG_CITY__SELECT = 'CATALOG_CITY__SELECT';

export const CATALOG_DEALER__REQUEST = 'CATALOG_DEALER__REQUEST';
export const CATALOG_DEALER__SUCCESS = 'CATALOG_DEALER__SUCCESS';
export const CATALOG_DEALER__FAIL = 'CATALOG_DEALER__FAIL';

export const CATALOG_ORDER__REQUEST = 'CATALOG_ORDER__REQUEST';
export const CATALOG_ORDER__SUCCESS = 'CATALOG_ORDER__SUCCESS';
export const CATALOG_ORDER__FAIL = 'CATALOG_ORDER__FAIL';

export const CATALOG_ORDER_COMMENT__FILL = 'CATALOG_ORDER_COMMENT__FILL';

export const EVENT_DEFAULT = 'EVENT_DEFAULT';
export const EVENT_REFRESH = 'EVENT_REFRESH';
export const EVENT_LOAD_MORE = 'EVENT_LOAD_MORE';
