export const CALL_ME__REQUEST = 'CALL_ME__REQUEST';
export const CALL_ME__SUCCESS = 'CALL_ME__SUCCESS';
export const CALL_ME__FAIL = 'CALL_ME__FAIL';

export const CONTACTS_MAP_USER_LOCATION__REQUEST = 'CONTACTS_MAP_USER_LOCATION__REQUEST';
export const CONTACTS_MAP_USER_LOCATION__DONE = 'CONTACTS_MAP_USER_LOCATION__DONE';
