export const CALL_ME__REQUEST = 'CALL_ME__REQUEST';
export const CALL_ME__SUCCESS = 'CALL_ME__SUCCESS';
export const CALL_ME__FAIL = 'CALL_ME__FAIL';

export const CONTACTS_MAP_AVAILABLE_NAVIAPPS__SET = 'CONTACTS_MAP_AVAILABLE_NAVIAPPS__SET';
export const CONTACTS_MAP_CHECK_AVAILABLE_NAVIAPPS__REQUEST = 'CONTACTS_MAP_CHECK_AVAILABLE_NAVIAPPS__REQUEST';
export const CONTACTS_MAP_CHECK_AVAILABLE_NAVIAPPS__DONE = 'CONTACTS_MAP_CHECK_AVAILABLE_NAVIAPPS__DONE';

export const CONTACTS_MAP_YNDX_NAVIGATOR = 'Яндекс.Навигатор';
export const CONTACTS_MAP_YNDX_MAPS = 'Яндекс.Карты';
export const CONTACTS_MAP_GOOGLE_MAPS = 'Google Maps';
export const CONTACTS_MAP_APPLE_MAPS = 'Apple Maps';
