export const CALL_ME__REQUEST = 'CALL_ME__REQUEST';
export const CALL_ME__SUCCESS = 'CALL_ME__SUCCESS';
export const CALL_ME__FAIL = 'CALL_ME__FAIL';

export const CONTACTS_MAP_AVAILABLE_NAVIAPPS__SET =
  'CONTACTS_MAP_AVAILABLE_NAVIAPPS__SET';
export const CONTACTS_MAP_CHECK_AVAILABLE_NAVIAPPS__REQUEST =
  'CONTACTS_MAP_CHECK_AVAILABLE_NAVIAPPS__REQUEST';
export const CONTACTS_MAP_CHECK_AVAILABLE_NAVIAPPS__DONE =
  'CONTACTS_MAP_CHECK_AVAILABLE_NAVIAPPS__DONE';

export const CONTACTS_CHAT_SEND__REQUEST = 'CONTACTS_CHAT_SEND__REQUEST';
export const CONTACTS_CHAT_SEND__SUCCESS = 'CONTACTS_CHAT_SEND__SUCCESS';
export const CONTACTS_CHAT_SEND__FAIL = 'CONTACTS_CHAT_SEND__FAIL';
