export const DEALERS_REGION__SELECT = 'DEALERS_REGION__SELECT';
export const DEALERS_BY_CITIES__SET = 'DEALERS_BY_CITIES__SET';

export const DEALER__REQUEST = 'DEALER__REQUEST';
export const DEALER__SUCCESS = 'DEALER__SUCCESS';
export const DEALER__SUCCESS__LOCAL = 'DEALER__SUCCESS__LOCAL';
export const CLEAR_LOCAL_DEALER = 'CLEAR_LOCAL_DEALER';
export const DEALER__FAIL = 'DEALER__FAIL';

export const DEALERS__REQUEST = 'DEALERS__REQUEST';
export const DEALERS__SUCCESS = 'DEALERS__SUCCESS';
export const DEALERS__FAIL = 'DEALERS__FAIL';

export const BRANDS__REQUEST = 'BRANDS__REQUEST';
export const BRANDS__SUCCESS = 'BRANDS__SUCCESS';
export const BRANDS__FAIL = 'BRANDS__FAIL';

export const CITIES__REQUEST = 'CITIES__REQUEST';
export const CITIES__SUCCESS = 'CITIES__SUCCESS';
export const CITIES__FAIL = 'CITIES__FAIL';
