export const DEALERS_REGION__SELECT = 'DEALERS_REGION__SELECT';
export const DEALERS_BY_CITIES__SET = 'DEALERS_BY_CITIES__SET';

export const DEALER__REQUEST = 'DEALER__REQUEST';
export const DEALER__SUCCESS = 'DEALER__SUCCESS';
export const DEALER__SUCCESS__LOCAL = 'DEALER__SUCCESS__LOCAL';
export const DEALER__FAIL = 'DEALER__FAIL';

export const DEALERS__REQUEST = 'DEALERS__REQUEST';
export const DEALERS__SUCCESS = 'DEALERS__SUCCESS';
export const DEALERS__FAIL = 'DEALERS__FAIL';
