export const COUNTRY__SELECT = 'COUNTRY__SELECT';

export const DEALER__SELECT = 'DEALER__SELECT';

export const DEALERS__REQUEST = 'DEALERS__REQUEST';
export const DEALERS__SUCCESS = 'DEALERS__SUCCESS';
export const DEALERS__FAIL = 'DEALERS__FAIL';
