-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgr6K0leBrQ0AOfK9R
psEarURu9ZZF5YtXVGmqZBoFoSGgCgYIKoZIzj0DAQehRANCAARHh7Ick3kiqczw
L+ATdbUHsgR+czVQfZPdKQmMGnwtEQbPvfuWQkIgZeS0+Br6Ahh9lqWwc9lz1WE+
T7HC7qsS
-----END PRIVATE KEY-----