export const INDICATORS__REQUEST = 'INDICATORS__REQUEST';
export const INDICATORS__SUCCESS = 'INDICATORS__SUCCESS';
export const INDICATORS__FAIL = 'INDICATORS__FAIL';

export const INDICATOR_ACTIVE__SET = 'INDICATOR_ACTIVE__SET';
