export const APP_PUSH_ACTION_SUBSCRIBE__SET = 'APP_PUSH_ACTION_SUBSCRIBE__SET';
export const APP_MENU_OPENED_COUNTER = 'APP_MENU_OPENED_COUNTER';
export const APP_ACTION_RATED = 'APP_ACTION_RATED';
export const APP_STORE_UPDATED = 'APP_STORE_UPDATED';

export const APP_SETTINGS_LOADED = 'APP_SETTINGS_LOADED';

export const APP_WALKTROUGH_SHOWN = 'APP_WALKTROUGH_SHOWN';

export const APP_LOADED = 'APP_LOADED';

export const MAIN_SCREEN__REQUEST = 'MAIN_SCREEN__REQUEST';
export const MAIN_SCREEN__SUCCESS = 'MAIN_SCREEN__SUCCESS';
export const MAIN_SCREEN__FAIL = 'MAIN_SCREEN__FAIL';

export const EVENT_DEFAULT = 'EVENT_DEFAULT';
export const EVENT_REFRESH = 'EVENT_REFRESH';
export const EVENT_LOAD_MORE = 'EVENT_LOAD_MORE';
