// export const APP_FCM_TOKEN__SET = 'APP_FCM_TOKEN__SET';
// export const APP_PREVIOUS_FCM_TOKEN__SET = 'APP_PREVIOUS_FCM_TOKEN__SET';
export const APP_PUSH_GRANTED__SET = 'APP_PUSH_GRANTED__SET';
export const APP_PUSH_ACTION_SUBSCRIBE__SET = 'APP_PUSH_ACTION_SUBSCRIBE__SET';
export const APP_MENU_OPENED_COUNTER = 'APP_MENU_OPENED_COUNTER';
export const APP_ACTION_RATED = 'APP_ACTION_RATED';
export const APP_STORE_UPDATED = 'APP_STORE_UPDATED';

export const EVENT_DEFAULT = 'EVENT_DEFAULT';
export const EVENT_REFRESH = 'EVENT_REFRESH';
export const EVENT_LOAD_MORE = 'EVENT_LOAD_MORE';
