export const PROFILE_NAME__FILL = 'PROFILE_NAME__FILL';
export const PROFILE_PHONE__FILL = 'PROFILE_PHONE__FILL';
export const PROFILE_EMAIL__FILL = 'PROFILE_EMAIL__FILL';
export const PROFILE_CAR__FILL = 'PROFILE_CAR__FILL';
export const PROFILE_CAR_NUMBER__FILL = 'PROFILE_CAR_NUMBER__FILL';
