export const PROFILE_NAME__FILL = 'PROFILE_NAME__FILL';
export const PROFILE_PHONE__FILL = 'PROFILE_PHONE__FILL';
export const PROFILE_EMAIL__FILL = 'PROFILE_EMAIL__FILL';
export const PROFILE_CAR__FILL = 'PROFILE_CAR__FILL';
export const PROFILE_CAR_NUMBER__FILL = 'PROFILE_CAR_NUMBER__FILL';
export const PROFILE_CAR_VIN__FILL = 'PROFILE_CAR_VIN__FILL';
export const PROFILE_LOGIN__FILL = 'PROFILE_LOGIN__FILL';
export const PROFILE_PASSWORD__FILL = 'PROFILE_PASSWORD__FILL';

export const LOGOUT = 'LOGOUT';
export const LOGIN__REQUEST = 'LOGIN__REQUEST';
export const LOGIN__SUCCESS = 'LOGIN__SUCCESS';
export const LOGIN__FAIL = 'LOGIN__FAIL';
export const REGISTER__REQUEST = 'REGISTER__REQUEST';
export const REGISTER__SUCCESS = 'REGISTER__SUCCESS';
export const REGISTER__FAIL = 'REGISTER__FAIL';

export const PROFILE_BONUS_LEVEL1__SET = 'PROFILE_BONUS_LEVEL1__SET';
export const PROFILE_BONUS_LEVEL2__SET = 'PROFILE_BONUS_LEVEL2__SET';
