export const NOTIFICATIONS__REQUEST = 'NOTIFICATIONS__REQUEST';
export const NOTIFICATIONS__SUCCESS = 'NOTIFICATIONS__SUCCESS';
export const NOTIFICATIONS__FAIL = 'NOTIFICATIONS__FAIL';

export const NOTIFICATIONS__LOCAL__REQUEST = 'NOTIFICATIONS__LOCAL__REQUEST';
export const NOTIFICATIONS__LOCAL__ADD = 'NOTIFICATIONS__LOCAL__ADD';
export const NOTIFICATIONS__LOCAL__REMOVE = 'NOTIFICATIONS__LOCAL__REMOVE';
export const NOTIFICATIONS__LOCAL__FAIL = 'NOTIFICATIONS__LOCAL__FAIL';
