// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'eu-west-1:bfc1f466-71bb-45d2-9027-5bd091437b46',
aws_cognito_region : 'eu-west-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'atlantm-hosting-mobilehub-1610695469',
aws_content_delivery_bucket_region : 'eu-west-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd28tnvyv2g90qa.cloudfront.net',
aws_mobile_analytics_app_id : '36f5721183b54260947b40706ab1816e',
aws_project_id : '1b9f0ae3-c2ef-476a-9f6b-4ef9546ff12e',
aws_project_name : 'Atlant-M',
aws_project_region : 'eu-west-1',
aws_resource_name_prefix : 'atlantm-mobilehub-1610695469',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});