# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean assembleRelease")
  end

desc "Submit a new Alpha Build to Google Play"
  lane :alpha do
    android_set_version_code(
      gradle_file: "app/build.gradle" # optional
    )
    gradle(task: "clean assembleRelease")

    upload_to_play_store(track: 'alpha')
    #slack(message: 'Successfully distributed a new alpha build')

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    android_set_version_code(
      gradle_file: "app/build.gradle" # optional
    )
    gradle(task: "clean assembleRelease")
    
    upload_to_play_store(track: 'beta')
    #slack(message: 'Successfully distributed a new beta build')

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
