export const REVIEWS__REQUEST = 'REVIEWS__REQUEST';
export const REVIEWS__SUCCESS = 'REVIEWS__SUCCESS';
export const REVIEWS__FAIL = 'REVIEWS__FAIL';
export const REVIEWS__RESET = 'REVIEWS__RESET';

export const REVIEWS_DATE_TO__FILL = 'REVIEWS_DATE_TO__FILL';
export const REVIEWS_DATE_FROM__FILL = 'REVIEWS_DATE_FROM__FILL';
export const REVIEWS_DATE_PERIOD__SELECT = 'REVIEWS_DATE_PERIOD__SELECT';

export const REVIEW__VISIT = 'REVIEW__VISIT';

export const REVIEW_DEALER_RATING__REQUEST = 'REVIEW_DEALER_RATING__REQUEST';
export const REVIEW_DEALER_RATING__SUCCESS = 'REVIEW_DEALER_RATING__SUCCESS';
export const REVIEW_DEALER_RATING__FAIL = 'REVIEW_DEALER_RATING__FAIL';

export const REVIEWS_RATING_FROM__SELECT = 'REVIEWS_RATING_FROM__SELECT';
export const REVIEWS_RATING_TO__SELECT = 'REVIEWS_RATING_TO__SELECT';
